version: '2.2'

services:
  # ROS Melodic
  ros-rplidar:
    image: husarion/rplidar
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0
    tty: true        # docker run -t
    command: roslaunch rplidar_ros rplidar.launch

  # ROS Noetic + ROS 2 Foxy
  bridge:
    image: ros:foxy-ros1-bridge
    restart: unless-stopped
    environment:
      - "ROS_MASTER_URI=http://ros-rplidar:11311"
    command: ros2 run ros1_bridge dynamic_bridge

  # ROS 2 Foxy
  desktopvnc:
    image: husarion/ros2-desktop-vnc:latest
    restart: unless-stopped
    volumes:
      - ./config.rviz:/root/.rviz2/default.rviz
    ports: 
      - 6080:80
    shm_size: '512m'

  husarnet:
      image: husarnet/husarnet
      restart: unless-stopped
      volumes:
          - /var/lib/husarnet  # This will persist your Husarnet Client keys, thus IP of the container will be stable/the same between (re)boots
      sysctls:
          - net.ipv6.conf.all.disable_ipv6=0  # Husarnet is using IPv6 for the internal connections
      cap_add:
          - NET_ADMIN
      devices:
          - /dev/net/tun
      env_file: 
          - ./.env  # create .env file in the same folder as Dockerfile and specify HOSTNAME and JOINCODE there